version: '3'
        #servicesは各コンテナを定義します
services:
        #dbは1つのコンテナ名です（１コンテナ１プロセス）
        #ローカルmysql version確認 → mysql  Ver 14.14 Distrib 5.6.47
        #DockerHubでmysql5.6を確認できたので5.6と記述
  db:
    image: mysql:5.6
        #environmentは環境変数を追加します
        #環境変数MYSQL_ROOT_PASSWORDに、今回はpasswordと入れます（パスは自由）
        #パスワードの直打ちは危険なので、環境変数を使って秘匿します
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
        #portsは公開用のポートで、ホスト側とコンテナ側の両方のポートを指定します（ ホスト側:コンテナ側 ）
        #ローカルMYSQLはポート確認すると3306を使用中なので、ホスト側は4306にします（4にした深い意味はありません）
        #ローカル側MYSQLは大抵は自動で3306になっているそうです
        #Sequelproにて4036(例として)を指定すると、DockerのMYSQLがSequelproで見れるようになります。
    ports:
      - "4306:3306"
      #webは1つのコンテナ名です（１コンテナ１プロセス）
      #buildはdockercompose.ymlを基点に指定フォルダー配下のDockerfileを元にコンテナを作成します。
      #指定は .  ルート （つまり、ルート直下に置いた先ほど作成したDockerfileを参照する、という記述です）
  web:
    build: .
      #commandは任意にコマンドを上書きできます。
      #bashはOSカーネルとユーザの橋渡しするプログラムシェルです
      #起動停止の繰り返しで起こるエラー「A server is already running.」の原因、pidをbuildのたび削除する（unicorn master KILLと同じですね）
      #Rails serverを立ち上げた際にURL(http://0.0.0.0:3000)にアクセス=localhost:3000
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
      #volumesではパスを指定するとDockerエンジンはボリュームを作成します
      #カレントディレクトリ(.)をapp_nameディレクトリにマウントします。
    volumes:
      - .:/app_name
      #portsは公開用のポートのことでホスト側とコンテナ側の両方のポートを指定します（ ホスト側:コンテナ側 ）
      #localhost:3000にアクセスするとコンテナの3000ポートにつながります
    ports:
      - "3000:3000"
      #depends_onはサービス間の依存関係を指定します
      #webコンテナ側からdbコンテナにdbの名前で接続できるようになります
      #docker-compose up を実行したら、web:コンテナのプロセスを開始するより前にdb:コンテナのプロセスを先に実行します
    depends_on:
      - db