lady = Category.create(name: "北海道地方")
lady_1 = lady.children.create(name: "道央")
lady_1.children.create([{name: "札幌カントリークラブ"},{name: "北海道ゴルフクラブ"},{name: "北海道ブルックスカントリークラブ"},{name: "北海道ポロトゴルフクラブ"},{name: "千歳空港カントリークラブ"},{name: "樽前カントリークラブ"}])
lady_2 = lady.children.create(name: "道北")
lady_2.children.create([{name: "ゴルフ5カントリー美唄コース"}])
lady_3 = lady.children.create(name: "道南")
lady_3.children.create([{name: "室蘭ゴルフクラブ"},{name: "大沼レイクゴルフクラブ"},{name: "北海道ポルトゴルフクラブ"}])
lady_4 = lady.children.create(name: "道東")
lady_4.children.create([{name: "札幌国際カントリークラブ島松コース"},{name: "桂ゴルフ倶楽部【GRAND PGM】"},{name: "札幌ゴルフ倶楽部輪厚コース"},{name: "ニドムクラシックコース"},{name: "北海道クラシックゴルフクラブ"}])

# lady_5 = lady.children.create(name: "ワンピース")
# lady_5.children.create([{name: "ミニワンピース"},{name: "ひざ丈ワンピース"},{name: "ロングワンピース"},{name: "その他"}])
# lady_6 = lady.children.create(name: "靴")
# lady_6.children.create([{name: "ハイヒール/パンプス"},{name: "ブーツ"},{name: "サンダル"},{name: "スニーカー"},{name: "ミュール"},{name: "モカシン"},{name: "ローファー/革靴"},{name: "フラットシューズ/バレエシューズ"},{name: "長靴/レインシューズ"},{name: "その他"}])
# lady_7 = lady.children.create(name: "ルームウェア/パジャマ")
# lady_7.children.create([{name: "パジャマ"},{name: "ルームウェア"}])
# lady_8 = lady.children.create(name: "レッグウェア")
# lady_8.children.create([{name: "ソックス"},{name: "スパッツ/レギンス"},{name: "ストッキング/タイツ"},{name: "レッグウォーマー"},{name: "その他"}])
# lady_9 = lady.children.create(name: "帽子")
# lady_9.children.create([{name: "ニットキャップ/ビーニー"},{name: "ハット"},{name: "ハンチング/ベレー帽"},{name: "キャップ"},{name: "キャスケット"},{name: "麦わら帽子"},{name: "その他"}])
# lady_10 = lady.children.create(name: "バッグ")
# lady_10.children.create([{name: "ハンドバッグ"},{name: "トートバッグ"},{name: "エコバッグ"},{name: "リュック/バックパック"},{name: "ボストンバッグ"},{name: "スポーツバッグ"},{name: "ショルダーバッグ"},{name: "クラッチバッグ"},{name: "ポーチ/バニティ"},{name: "ボディバッグ/ウェストバッグ"},{name: "マザーズバッグ"},{name: "メッセンジャーバッグ"},{name: "ビジネスバッグ"},{name: "旅行用バッグ/キャリーバッグ"},{name: "ショップ袋"},{name: "和装用バッグ"},{name: "かごバッグ"},{name: "その他"}])
# lady_11 = lady.children.create(name: "アクセサリー")
# lady_11.children.create([{name: "ネックレス"},{name: "ブレスレット"},{name: "バングル/リストバンド"},{name: "リング"},{name: "ピアス(片耳用)"},{name: "ピアス(両耳用)"},{name: "イヤリング"},{name: "アンクレット"},{name: "ブローチ/コサージュ"},{name: "チャーム"},{name: "その他"}])
# lady_12 = lady.children.create(name: "ヘアアクセサリー")
# lady_12.children.create([{name: "ヘアゴム/シュシュ"},{name: "ヘアバンド/カチューシャ"},{name: "ヘアピン"},{name: "その他"}])
# lady_13 = lady.children.create(name: "小物")
# lady_13.children.create([{name: "長財布"},{name: "折り財布"},{name: "コインケース/小銭入れ"},{name: "名刺入れ/定期入れ"},{name: "キーケース"},{name: "キーホルダー"},{name: "手袋/アームカバー"},{name: "ハンカチ"},{name: "マフラー/ショール"},{name: "ストール/スヌード"},{name: "バンダナ/スカーフ"},{name: "ネックウォーマー"},{name: "サスペンダー/ベルト"},{name: "サングラス/メガネ"},{name: "手帳"},{name: "傘"},{name: "レインコート/ポンチョ"},{name: "ミラー"},{name: "タバコグッズ"},{name: "その他"}])
# lady_14 = lady.children.create(name: "時計")
# lady_14.children.create([{name: "腕時計(アナログ)"},{name: "腕時計(デジタル)"},{name: "ラバーベルト"},{name: "レザーベルト"},{name: "金属ベルト"},{name: "その他"}])
# lady_15 = lady.children.create(name: "ウィッグ/エクステ")
# lady_15.children.create([{name: "前髪ウィッグ"},{name: "ロングストレート"},{name: "ロングカール"},{name: "ショートストレート"},{name: "ショートカール"},{name: "その他"}])
# lady_16 = lady.children.create(name: "浴衣/水着")
# lady_16.children.create([{name: "浴衣"},{name: "着物"},{name: "振袖"},{name: "長襦袢/半襦袢"},{name: "水着セパレート"},{name: "水着ワンピース"},{name: "水着スポーツ用"},{name: "その他"}])
# lady_17 = lady.children.create(name: "スーツ/フォーマル/ドレス")
# lady_17.children.create([{name: "スカートスーツ上下"},{name: "パンツスーツ上下"},{name: "ドレス"},{name: "パーティーバッグ"},{name: "シューズ"},{name: "ウェディング"},{name: "その他"}])
# lady_18 = lady.children.create(name: "マタニティ")
# lady_18.children.create([{name: "トップス"},{name: "アウター"},{name: "インナー"},{name: "ワンピース"},{name: "パンツ/スパッツ"},{name: "スカート"},{name: "パジャマ"},{name: "授乳服"},{name: "その他"}])
# lady_19 = lady.children.create(name: "その他")
# lady_19.children.create([{name: "コスプレ"},{name: "下着"},{name: "その他"}])

men = Category.create(name: "東北地方")
men_1 = men.children.create(name: "青森県")
men_1.children.create([{name: "青森スプリング・ゴルフクラブ"},{name: "青森カントリー倶楽部"},{name: "津軽高原ゴルフ場"},{name: "青森ロイヤルゴルフクラブ"},{name: "みちのく国際ゴルフ倶楽部"},{name: "夏泊ゴルフリンクス"},{name: "びわの平ゴルフ倶楽部"},{name: "東奥カントリークラブ"}])
men_2 = men.children.create(name: "岩手県")
men_2.children.create([{name: "岩手ゴルフ倶楽部"},{name: "南岩手カントリークラブ"},{name: "岩手沼宮内カントリークラブ"},{name: "岩手県花巻広域公園県民ゴルフ場"},{name: "みちのく古都カントリークラブ"},{name: "安比高原ゴルフクラブ"}])
men_3 = men.children.create(name: "秋田県")
men_3.children.create([{name: "秋田森岳温泉３６ゴルフ場"},{name: "秋田椿台カントリークラブ"},{name: "秋田カントリー倶楽部"},{name: "秋田北空港クラシックゴルフ倶楽部"},{name: "男鹿ゴルフクラブ"},{name: "新・秋田ウインズカントリークラブ"},{name: "ノースハンプトンゴルフ倶楽部"},{name: "大野台ゴルフクラブ"}])
men_4 = men.children.create(name: "宮城県")
men_4.children.create([{name: "仙台南ゴルフ倶楽部"},{name: "仙台グリーンゴルフクラブ"},{name: "表蔵王国際ゴルフクラブ"},{name: "仙台クラシックゴルフ俱楽部"},{name: "ミヤヒル３６ゴルフクラブ"},{name: "西仙台カントリークラブ"},{name: "宮城カントリークラブ"},{name: "泉国際ゴルフ倶楽部"}])
men_5 = men.children.create(name: "山形県")
men_5.children.create([{name: "大石田ゴルフクラブ"},{name: "山形ゴルフ倶楽部"},{name: "蔵王カントリークラブ"},{name: "天童カントリークラブ"},{name: "新庄アーデンゴルフ倶楽部 山形 ゴルフ場"},{name: "県民ゴルフ場"},{name: "さくらんぼカントリークラブ"},{name: "湯の浜カントリークラブ"},{name: "朝日カントリークラブ"}])
men_6 = men.children.create(name: "福島県")
men_6.children.create([{name: "大玉カントリークラブ"},{name: "郡山ゴルフ倶楽部"},{name: "矢吹ゴルフ倶楽部"},{name: "新ゲインズボローカントリー倶楽部"},{name: "福島ゴルフ倶楽部民報コース"}])
# men_7 = men.children.create(name: "帽子")
# men_7.children.create([{name: "キャップ"},{name: "ハット"},{name: "ニットキャップ/ビーニー"},{name: "ハンチング/ベレー帽"},{name: "キャスケット"},{name: "サンバイザー"},{name: "その他"}])
# men_8 = men.children.create(name: "アクセサリー")
# men_8.children.create([{name: "ネックレス"},{name: "ブレスレット"},{name: "バングル/リストバンド"},{name: "リング"},{name: "ピアス(片耳用)"},{name: "ピアス(両耳用)"},{name: "アンクレット"},{name: "その他"}])
# men_9 = men.children.create(name: "小物")
# men_9.children.create([{name: "長財布"},{name: "折り財布/マネークリップ"},{name: "コインケース/小銭入れ"},{name: "名刺入れ/定期入れ"},{name: "キーケース/キーホルダー"},{name: "ネクタイ"},{name: "手袋"},{name: "マフラー/ストール"},{name: "バンダナ/ハンカチ"},{name: "ネックウォーマー"},{name: "ベルト/サスペンダー"},{name: "ウォレットチェーン"},{name: "サングラス/メガネ"},{name: "手帳"},{name: "ストラップ"},{name: "ネクタイピン"},{name: "傘"},{name: "レインコート"},{name: "その他"}])
# men_10 = men.children.create(name: "時計")
# men_10.children.create([{name: "腕時計(アナログ)"},{name: "腕時計(デジタル)"},{name: "ラバーベルト"},{name: "レザーベルト"},{name: "金属ベルト"},{name: "その他"}])
# men_11 = men.children.create(name: "水着")
# men_11.children.create([{name: "一般水着"},{name: "スポーツ用"},{name: "アクセサリー"},{name: "その他"}])
# men_12 = men.children.create(name: "レッグウェア")
# men_12.children.create([{name: "ソックス"},{name: "レギンス/スパッツ"},{name: "レッグウォーマー"},{name: "その他"}])
# men_13 = men.children.create(name: "アンダーウェア")
# men_13.children.create([{name: "トランクス"},{name: "ボクサーパンツ"},{name: "その他"}])
# men_14 = men.children.create(name: "その他")
# men_14.children.create([{name: "すべて"}])

baby_kids = Category.create(name: "関東地方")
baby_kids_1 = baby_kids.children.create(name: "茨城県")
baby_kids_1.children.create([{name: "31カントリークラブ"},{name: "霞台カントリークラブ【アコーディア・ゴルフ】"},{name: "アジア取手カントリー倶楽部"},{name: "茨城ゴルフ倶楽部"},{name: "サミットゴルフクラブ"},{name: "猿島カントリー倶楽部"},{name: "かすみがうらゴルフクラブ"}])
baby_kids_2 = baby_kids.children.create(name: "栃木県")
baby_kids_2.children.create([{name: "大平台カントリークラブ【アコーディア・ゴルフ】"},{name: "佐野ゴルフクラブ"},{name: "唐沢ゴルフ倶楽部唐沢コース"},{name: "足利渡良瀬ゴルフ場"},{name: "小山ゴルフクラブ"},{name: "JGM宇都宮ゴルフクラブ"},{name: "ゴールド栃木プレジデントカントリークラブ"}])
baby_kids_3 = baby_kids.children.create(name: "群馬県")
baby_kids_3.children.create([{name: "板倉ゴルフ場"},{name: "新玉村ゴルフ場"},{name: "鳳凰ゴルフ倶楽部"},{name: "関越ハイランドゴルフクラブ【アコーディア・ゴルフ】"},{name: "ＰＧＭ富岡カントリークラブ ノースコース【PGM】"},{name: "前橋ゴルフ場"},{name: "大間々ゴルフクラブ"},{name: "玉村ゴルフ場"}])
baby_kids_4 = baby_kids.children.create(name: "埼玉県")
baby_kids_4.children.create([{name: "朝霞パブリックゴルフ場"},{name: "浦和ゴルフ倶楽部"},{name: "大宮カントリークラブ"},{name: "戸田パブリックゴルフコース"},{name: "川口市浮間ゴルフ場"},{name: "大宮国際カントリークラブ"},{name: "川越グリーンクロス【PGM】"},{name: "リバーサイドフェニックスゴルフクラブ"},{name: "川口パブリックゴルフ場"}])
baby_kids_5 = baby_kids.children.create(name: "千葉県")
baby_kids_5.children.create([{name: "クリアビューゴルフクラブ&ホテル【PGM】"},{name: "鎌ヶ谷カントリークラブ"},{name: "アコーディア・ゴルフ 習志野カントリークラブ"},{name: "泉カントリー倶楽部"},{name: "カメリアヒルズカントリークラブ"},{name: "かずさカントリークラブ 【アコーディア・ゴルフ】"},{name: "鹿野山ゴルフ倶楽部"}])
baby_kids_6 = baby_kids.children.create(name: "神奈川県")
baby_kids_6.children.create([{name: "川崎国際生田緑地ゴルフ場"},{name: "大厚木カントリークラブ 本コース【アコーディア・ゴルフ】"},{name: "横浜カントリークラブ"},{name: "鎌倉パブリックゴルフ場"},{name: "神奈川カントリークラブ"},{name: "津久井湖ゴルフ倶楽部"},{name: "相模原ゴルフクラブ"},{name: "川崎リバーサイドパークゴルフ場"}])
baby_kids_7 = baby_kids.children.create(name: "東京都")
baby_kids_7.children.create([{name: "赤羽ゴルフ倶楽部"},{name: "若洲ゴルフリンクス"},{name: "江戸川ラインゴルフ ショートコース"},{name: "荒川・扇河川健康公園パークゴルフ場"},{name: "小金井カントリー倶楽部"},{name: "扇ゴルフ練習場"}])
# baby_kids_8 = baby_kids.children.create(name: "子ども用ファッション小物")
# baby_kids_8.children.create([{name: "靴下/スパッツ"},{name: "帽子"},{name: "エプロン"},{name: "サスペンダー"},{name: "タイツ"},{name: "ハンカチ"},{name: "バンダナ"},{name: "ベルト"},{name: "マフラー"},{name: "傘"},{name: "手袋"},{name: "バッグ"},{name: "その他"}])
# baby_kids_9 = baby_kids.children.create(name: "おむつ/トイレ/バス")
# baby_kids_9.children.create([{name: "おむつ用品"},{name: "おまる/補助便座"},{name: "トレーニングパンツ"},{name: "ベビーバス"},{name: "お風呂用品"},{name: "その他"}])
# baby_kids_10 = baby_kids.children.create(name: "外出/移動用品")
# baby_kids_10.children.create([{name: "ベビーカー"},{name: "抱っこひも/スリング"},{name: "チャイルドシート"},{name: "その他"}])
# baby_kids_11 = baby_kids.children.create(name: "授乳/食事")
# baby_kids_11.children.create([{name: "ミルク"},{name: "ベビーフード"},{name: "ベビー用食器"},{name: "その他"}])
# baby_kids_12 = baby_kids.children.create(name: "ベビー家具/寝具/室内用品")
# baby_kids_12.children.create([{name: "ベッド"},{name: "布団/毛布"},{name: "イス"},{name: "たんす"},{name: "その他"}])
# baby_kids_13 = baby_kids.children.create(name: "おもちゃ")
# baby_kids_13.children.create([{name: "おふろのおもちゃ"},{name: "がらがら"},{name: "オルゴール"},{name: "ベビージム"},{name: "手押し車/カタカタ"},{name: "知育玩具"},{name: "その他"}])
# baby_kids_14 = baby_kids.children.create(name: "行事/記念品")
# baby_kids_14.children.create([{name: "お宮参り用品"},{name: "お食い初め用品"},{name: "アルバム"},{name: "手形/足形"},{name: "その他"}])
# baby_kids_15 = baby_kids.children.create(name: "その他")
# baby_kids_15.children.create([{name: "母子手帳用品"},{name: "その他"}])

interior_residence_accessory = Category.create(name: "中部地方")
interior_residence_accessory_1 = interior_residence_accessory.children.create(name: "新潟県")
interior_residence_accessory_1.children.create([{name: "新潟ゴルフ倶楽部"},{name: "新潟サンライズゴルフコース"},{name: "新津カントリークラブ"},{name: "フォレストカントリー倶楽部"},{name: "中峰ゴルフ倶楽部【PGM】"},{name: "湯田上カントリークラブ"},{name: "イーストヒルゴルフクラブ"},{name: "笹神五頭ゴルフ倶楽部"},{name: "サウンドゴルフＭＡＫＩ"}])
interior_residence_accessory_2 = interior_residence_accessory.children.create(name: "富山県")
interior_residence_accessory_2.children.create([{name: "小杉カントリークラブ"},{name: "千羽平ゴルフクラブ"},{name: "富山カントリークラブ"},{name: "棚山ゴルフ倶楽部"},{name: "高岡カントリー倶楽部"},{name: "富山ゴルフ"},{name: "富山市パークゴルフ場"},{name: "魚津国際カントリークラブ"},{name: "小杉パークゴルフクラブパークゴルフ場"}])
interior_residence_accessory_3 = interior_residence_accessory.children.create(name: "石川県")
interior_residence_accessory_3.children.create([{name: "石川ゴルフ倶楽部【アコーディア・ゴルフ】"},{name: "片山津ゴルフ倶楽部 片山津ゴルフ場"},{name: "能登ゴルフ倶楽部"},{name: "チェリーゴルフクラブ金沢東コース"},{name: "チェリー金沢ゴルフクラブ"},{name: "ゴルフクラブ・ツインフィールズ"},{name: "金沢セントラルカントリー倶楽部"},{name: "加賀セントラルゴルフ倶楽部"}])
interior_residence_accessory_4 = interior_residence_accessory.children.create(name: "福井県")
interior_residence_accessory_4.children.create([{name: "芦原ゴルフクラブ"},{name: "フォーレスト福井ゴルフクラブ"},{name: "ジャパンセントラルゴルフ倶楽部"},{name: "敦賀国際ゴルフ倶楽部"},{name: "杉ノ木台ゴルフクラブ"},{name: "わかさカントリー倶楽部"},{name: "越前カントリークラブ"},{name: "越前武生カントリークラブ"},{name: "福井国際カントリークラブ"}])
interior_residence_accessory_5 = interior_residence_accessory.children.create(name: "山梨県")
interior_residence_accessory_5.children.create([{name: "メイプルポイントゴルフクラブ"},{name: "大月ガーデンゴルフクラブ【アコーディア・ゴルフ】"},{name: "勝沼ゴルフコース"},{name: "春日居ゴルフ倶楽部"},{name: "西東京ゴルフ倶楽部"},{name: "上野原カントリークラブ"},{name: "昇仙峡カントリークラブ"},{name: "都ゴルフ倶楽部"},{name: "レイクウッドゴルフクラブサンパーク明野コース"},{name: "甲府国際カントリークラブ"}])
interior_residence_accessory_6 = interior_residence_accessory.children.create(name: "長野県")
interior_residence_accessory_6.children.create([{name: "信州伊那国際ゴルフクラブ"},{name: "小諸高原ゴルフクラブ"},{name: "塩嶺カントリークラブ"},{name: "南長野ゴルフ倶楽部"},{name: "望月東急ゴルフクラブ"},{name: "佐久リゾートゴルフ倶楽部"},{name: "軽井沢72ゴルフ"},{name: "川中嶋カントリークラブ"},{name: "グランディ軽井沢ゴルフクラブ"},{name: "蓼科高原カントリークラブ"}])
interior_residence_accessory_7 = interior_residence_accessory.children.create(name: "岐阜県")
interior_residence_accessory_7.children.create([{name: "岐阜スプリングゴルフクラブ"},{name: "岐阜稲口ゴルフ倶楽部"},{name: "明智ゴルフ倶楽部 ひるかわゴルフ場"},{name: "サンクラシックゴルフクラブ【アコーディア・ゴルフ】"},{name: "新陽カントリー倶楽部【アコーディア・ゴルフ】"},{name: "名岐国際ゴルフ倶楽部"}])
interior_residence_accessory_8 = interior_residence_accessory.children.create(name: "静岡県")
interior_residence_accessory_8.children.create([{name: "ギャツビイゴルフクラブ"},{name: "ベルビュー長尾ゴルフ倶楽部"},{name: "十里木カントリークラブ【アコーディア・ゴルフ】"},{name: "伊豆国際カントリークラブ【アコーディア・ゴルフ】"},{name: "富士エースゴルフ倶楽部"}])
interior_residence_accessory_9 = interior_residence_accessory.children.create(name: "愛知県")
interior_residence_accessory_9.children.create([{name: "名古屋ゴルフ倶楽部 和合コース"},{name: "パインフラット ゴルフクラブ"},{name: "ウッドフレンズ森林公園ゴルフ場"},{name: "加茂ゴルフ倶楽部"},{name: "サン・ベルグラビアカントリー倶楽部"},{name: "ゴルフ倶楽部大樹 豊田コース"}])
# interior_residence_accessory_10 = interior_residence_accessory.children.create(name: "寝具")
# interior_residence_accessory_10.children.create([{name: "布団/毛布"},{name: "枕"},{name: "シーツ/カバー"},{name: "その他"}])
# interior_residence_accessory_11 = interior_residence_accessory.children.create(name: "インテリア小物")
# interior_residence_accessory_11.children.create([{name: "ごみ箱"},{name: "ウェルカムボード"},{name: "オルゴール"},{name: "クッション/クッションカバー"},{name: "スリッパラック"},{name: "ティッシュボックス"},{name: "バスケット/かご"},{name: "フォトフレーム"},{name: "モビール"},{name: "花瓶"},{name: "灰皿"},{name: "傘立て"},{name: "小物入れ"},{name: "置時計"},{name: "掛時計/柱時計"},{name: "鏡(立て掛け式)"},{name: "鏡(壁掛け式)"},{name: "置物/風鈴"},{name: "植物/観葉植物"},{name: "その他"}])
# interior_residence_accessory_12 = interior_residence_accessory.children.create(name: "季節/年中行事")
# interior_residence_accessory_12.children.create([{name: "正月"},{name: "成人式"},{name: "バレンタインデー"},{name: "ひな祭り"},{name: "子どもの日"},{name: "母の日"},{name: "父の日"},{name: "父の日"},{name: "サマーギフト/お中元"},{name: "夏/夏休み"},{name: "ハロウィン"},{name: "敬老の日"},{name: "七五三"},{name: "お歳暮"},{name: "クリスマス"},{name: "冬一般"},{name: "その他"}])
# interior_residence_accessory_13 = interior_residence_accessory.children.create(name: "その他")
# interior_residence_accessory_13.children.create([{name: "すべて"}])

book_music_game = Category.create(name: "近畿地方")
book_music_game_1 = book_music_game.children.create(name: "三重県")
book_music_game_1.children.create([{name: "霞ゴルフクラブ"},{name: "桑名国際ゴルフ倶楽部"},{name: "ココパリゾートクラブ三重フェニックスゴルフコース"},{name: "ココパリゾートクラブ 三重白山ゴルフコース"},{name: "美杉ゴルフ倶楽部"},{name: "エクセレントゴルフクラブ 伊勢二見コース"},{name: "四日市の里ゴルフクラブ【アコーディア・ゴルフ】"},{name: "白山ヴィレッジゴルフコース"},{name: "近鉄浜島カンツリークラブ"},{name: "エクセレントゴルフクラブ 一志温泉コース"}])
book_music_game_2 = book_music_game.children.create(name: "滋賀県")
book_music_game_2.children.create([{name: "コムウッドゴルフクラブ"},{name: "比良ゴルフ倶楽部"},{name: "瀬田ゴルフコース"},{name: "大津カントリークラブ東コース【アコーディア・ゴルフ】"},{name: "近江ヒルズゴルフ倶楽部【PGM】"},{name: "タラオカントリークラブ"},{name: "皇子山カントリークラブ"}])
book_music_game_3 = book_music_game.children.create(name: "京都府")
book_music_game_3.children.create([{name: "京都ゴルフ倶楽部 上賀茂コース"},{name: "京都大原パブリックコース"},{name: "東城陽ゴルフ倶楽部"},{name: "宇治カントリークラブ"},{name: "クラウンヒルズ京都ゴルフ倶楽部"}])
book_music_game_4 = book_music_game.children.create(name: "大阪府")
book_music_game_4.children.create([{name: "大阪パブリックゴルフ場"},{name: "大阪ゴルフクラブ"},{name: "光丘パブリックゴルフ場"},{name: "牧野パークゴルフ場"},{name: "あいがわゴルフコース"},{name: "樟葉パブリック・ゴルフ・コース"},{name: "枚方国際ゴルフ倶楽部【PGM】"}])
book_music_game_5 = book_music_game.children.create(name: "兵庫県")
book_music_game_5.children.create([{name: "神戸グランドヒルゴルフクラブ【PGM】"},{name: "神戸パインウッズゴルフクラブ"},{name: "愛宕原ゴルフ倶楽部【アコーディア・ゴルフ】"},{name: "明石ゴルフ倶楽部"},{name: "神戸ゴルフ倶楽部"},{name: "北神戸ゴルフ場"},{name: "関西クラシックゴルフ倶楽部"},{name: "ロータリーゴルフ倶楽部"},{name: "ABCゴルフ倶楽部"}])
book_music_game_6 = book_music_game.children.create(name: "奈良県")
book_music_game_6.children.create([{name: "奈良万葉カンツリー倶楽部【アコーディア・ゴルフ】"},{name: "奈良名阪ゴルフクラブ"},{name: "天理ゴルフ倶楽部"},{name: "新奈良ゴルフ倶楽部"},{name: "奈良パブリックゴルフ場"},{name: "ムロウ３６ゴルフクラブ"},{name: "グランデージゴルフ倶楽部"}])
book_music_game_7 = book_music_game.children.create(name: "和歌山県")
book_music_game_7.children.create([{name: "和歌山カントリー倶楽部"},{name: "紀伊高原ゴルフクラブ"},{name: "ラ・グレースゴルフ倶楽部 和歌山コース"},{name: "レオグラードゴルフクラブ"},{name: "紀南カントリークラブゴルフ場"},{name: "日本ダイヤモンドゴルフ倶楽部"}])

toy_hobby_goods = Category.create(name: "中国地方")
toy_hobby_goods_1 = toy_hobby_goods.children.create(name: "鳥取県")
toy_hobby_goods_1.children.create([{name: "米子ゴルフ場"},{name: "旭国際浜村温泉ゴルフ倶楽部"},{name: "鳥取ゴルフ倶楽部"},{name: "大山平原ゴルフクラブ"},{name: "郡家ゴルフ倶楽部"},{name: "大山ゴルフクラブ"},{name: "鳥取カントリー倶楽部 吉岡温泉コース"},{name: "神田ゴルフクラブ"},{name: "グリーンパーク大山ゴルフ倶楽部"},{name: "光好カントリークラブ"}])
toy_hobby_goods_2 = toy_hobby_goods.children.create(name: "島根県")
toy_hobby_goods_2.children.create([{name: "島根ゴルフ倶楽部"},{name: "クラシック島根カントリークラブ"},{name: "玉造温泉カントリークラブ"},{name: "出雲空港カントリー倶楽部"},{name: "出雲ゴルフ倶楽部"}])
toy_hobby_goods_3 = toy_hobby_goods.children.create(name: "岡山県")
toy_hobby_goods_3.children.create([{name: "岡山北ゴルフ倶楽部"},{name: "新岡山ゴルフクラブ"},{name: "岡山空港ゴルフコース"},{name: "岡山ゴルフ倶楽部"},{name: "ザ・オークレットゴルフクラブ"},{name: "岡山国際ゴルフ倶楽部【PGM】"},{name: "井原ゴルフ倶楽部"},{name: "山陽ゴルフ倶楽部"}])
toy_hobby_goods_4 = toy_hobby_goods.children.create(name: "広島県")
toy_hobby_goods_4.children.create([{name: "広島安佐ゴルフクラブ"},{name: "郷原カントリークラブ"},{name: "広島ゴルフ倶楽部 鈴が峰ゴルフコース"},{name: "東広島カントリークラブ【PGM】"},{name: "竹原カントリークラブ"},{name: "リージャスクレストゴルフクラブ"},{name: "チェリーゴルフクラブ吉和の森コース"},{name: "千代田ゴルフ倶楽部"},{name: "グリーンバーズゴルフ倶楽部"},{name: "芸南カントリークラブ"},{name: "尾道カントリークラブ宇根山コース"},{name: "久井カントリークラブ"},{name: "瀬戸内ゴルフリゾート"},{name: "広島紅葉カントリークラブ"}])
toy_hobby_goods_5 = toy_hobby_goods.children.create(name: "山口県")
toy_hobby_goods_5.children.create([{name: "豊田湖ゴルフクラブ"},{name: "新山口カンツリー倶楽部"},{name: "泉水原ゴルフクラブ"},{name: "ユニマット山口ゴルフ倶楽部"},{name: "山陽国際ゴルフクラブ【アコーディア・ゴルフ】"},{name: "下関ゴールデンゴルフクラブ"},{name: "山口レインボーヒルズ関門菊川ゴルフクラブ"},{name: "厚狭ゴルフ倶楽部"}])
# toy_hobby_goods_6 = toy_hobby_goods.children.create(name: "楽器/器材")
# toy_hobby_goods_6.children.create([{name: "エレキギター"},{name: "アコースティックギター"},{name: "ベース"},{name: "エフェクター"},{name: "アンプ"},{name: "弦楽器"},{name: "管楽器"},{name: "鍵盤楽器"},{name: "打楽器"},{name: "和楽器"},{name: "楽譜/スコア"},{name: "レコーディング/PA機器"},{name: "DJ機器"},{name: "DTM/DAW"},{name: "その他"}])
# toy_hobby_goods_7 = toy_hobby_goods.children.create(name: "コレクション")
# toy_hobby_goods_7.children.create([{name: "武具"},{name: "使用済切手/官製はがき"},{name: "旧貨幣/金貨/銀貨/記念硬貨"},{name: "印刷物"},{name: "ノベルティグッズ"},{name: "その他"}])
# toy_hobby_goods_8 = toy_hobby_goods.children.create(name: "ミリタリー")
# toy_hobby_goods_8.children.create([{name: "トイガン"},{name: "個人装備"},{name: "その他"}])
# toy_hobby_goods_9 = toy_hobby_goods.children.create(name: "美術品")
# toy_hobby_goods_9.children.create([{name: "陶芸"},{name: "ガラス"},{name: "漆芸"},{name: "金属工芸"},{name: "絵画/タペストリ"},{name: "版画"},{name: "彫刻/オブジェクト"},{name: "書"},{name: "写真"},{name: "その他"}])
# toy_hobby_goods_10 = toy_hobby_goods.children.create(name: "アート用品")
# toy_hobby_goods_10.children.create([{name: "画材"},{name: "額縁"},{name: "その他"}])
# toy_hobby_goods_11 = toy_hobby_goods.children.create(name: "その他")
# toy_hobby_goods_11.children.create([{name: "トランプ/UNO"},{name: "カルタ/百人一首"},{name: "ダーツ"},{name: "ビリヤード"},{name: "麻雀"},{name: "パズル/ジグソーパズル"},{name: "囲碁/将棋"},{name: "オセロ/チェス"},{name: "人生ゲーム"},{name: "野球/サッカーゲーム"},{name: "スポーツ"},{name: "三輪車/乗り物"},{name: "ヨーヨー"},{name: "模型製作用品"},{name: "鉄道"},{name: "航空機"},{name: "アマチュア無線"},{name: "パチンコ/パチスロ"},{name: "その他"}])

cosme_perfume_beauty = Category.create(name: "四国地方")
cosme_perfume_beauty_1 = cosme_perfume_beauty.children.create(name: "徳島県")
cosme_perfume_beauty_1.children.create([{name: "サンピアゴルフクラブ"},{name: "コート・ベール徳島ゴルフクラブ"},{name: "Ｊクラシックゴルフクラブ"},{name: "タカガワ西徳島ゴルフ倶楽部"},{name: "徳島ゴルフ倶楽部"},{name: "タカガワ東徳島ゴルフ倶楽部"},{name: "鳴門カントリークラブ"},{name: "眉山カントリークラブ"},{name: "四国カントリークラブ"}])
cosme_perfume_beauty_2 = cosme_perfume_beauty.children.create(name: "香川県")
cosme_perfume_beauty_2.children.create([{name: "アイシエリエールゴルフクラブドウ"},{name: "タカガワ新琴南ゴルフ倶楽部"},{name: "高松グランドカントリークラブ"},{name: "ロイヤル高松カントリークラブ"},{name: "高松カントリー倶楽部"},{name: "讃岐カントリークラブ"},{name: "高松ゴールドカントリー倶楽部"},{name: "志度カントリークラブ"},{name: "満濃ヒルズカントリークラブ"},{name: "小豆島シーサイドゴルフクラブ"},{name: "サンライズヒルズ・カントリークラブ"},{name: "アルファ津田カントリークラブ"},{name: "高松パブリックゴルフコース"}])
cosme_perfume_beauty_3 = cosme_perfume_beauty.children.create(name: "愛媛県")
cosme_perfume_beauty_3.children.create([{name: "タカガワ新伊予ゴルフ倶楽部"},{name: "奥道後ゴルフクラブ"},{name: "大洲ゴルフ倶楽部"},{name: "松山ゴルフ倶楽部"},{name: "西条ゴルフ倶楽部"},{name: "道後ゴルフ倶楽部"},{name: "北条カントリー倶楽部"},{name: "新居浜カントリー倶楽部"},{name: "高原ゴルフ倶楽部"}])
cosme_perfume_beauty_4 = cosme_perfume_beauty.children.create(name: "高知県")
cosme_perfume_beauty_4.children.create([{name: "土佐カントリークラブ"},{name: "スカイベイゴルフクラブ"},{name: "Kochi黒潮カントリークラブ"},{name: "パシフィックゴルフクラブ"},{name: "錦山カントリークラブ"},{name: "グリーンフィールゴルフ倶楽部"},{name: "土佐ユートピアカントリークラブ"},{name: "四万十カントリークラブ"}])
# cosme_perfume_beauty_5 = cosme_perfume_beauty.children.create(name: "スキンケア/基礎化粧品")
# cosme_perfume_beauty_5.children.create([{name: "化粧水/ローション"},{name: "乳液/ミルク"},{name: "美容液"},{name: "フェイスクリーム"},{name: "洗顔料"},{name: "クレンジング/メイク落とし"},{name: "パック/フェイスマスク"},{name: "ジェル/ゲル"},{name: "ブースター/導入液"},{name: "アイケア"},{name: "リップケア"},{name: "トライアルセット/サンプル"},{name: "洗顔グッズ"},{name: "その他"}])
# cosme_perfume_beauty_6 = cosme_perfume_beauty.children.create(name: "ヘアケア")
# cosme_perfume_beauty_6.children.create([{name: "シャンプー"},{name: "トリートメント"},{name: "コンディショナー"},{name: "リンス"},{name: "スタイリング剤"},{name: "カラーリング剤"},{name: "ブラシ"},{name: "その他"}])
# cosme_perfume_beauty_7 = cosme_perfume_beauty.children.create(name: "ボディケア")
# cosme_perfume_beauty_7.children.create([{name: "オイル/クリーム"},{name: "ハンドクリーム"},{name: "ローション"},{name: "日焼け止め/サンオイル"},{name: "ボディソープ"},{name: "入浴剤"},{name: "制汗/デオドラント"},{name: "フットケア"},{name: "その他"}])
# cosme_perfume_beauty_8 = cosme_perfume_beauty.children.create(name: "オーラルケア")
# cosme_perfume_beauty_8.children.create([{name: "口臭防止/エチケット用品"},{name: "歯ブラシ"},{name: "その他"}])
# cosme_perfume_beauty_9 = cosme_perfume_beauty.children.create(name: "リラクゼーション")
# cosme_perfume_beauty_9.children.create([{name: "エッセンシャルオイル"},{name: "芳香器"},{name: "お香/香炉"},{name: "キャンドル"},{name: "リラクゼーショングッズ"},{name: "その他"}])
# cosme_perfume_beauty_10 = cosme_perfume_beauty.children.create(name: "ダイエット")
# cosme_perfume_beauty_10.children.create([{name: "ダイエット食品"},{name: "エクササイズ用品"},{name: "体重計"},{name: "体脂肪計"},{name: "その他"}])
# cosme_perfume_beauty_11 = cosme_perfume_beauty.children.create(name: "その他")
# cosme_perfume_beauty_11.children.create([{name: "健康用品"},{name: "看護/介護用品"},{name: "救急/衛生用品"},{name: "その他"}])

appliance_smartphone_camera = Category.create(name: "九州地方")
appliance_smartphone_camera_1 = appliance_smartphone_camera.children.create(name: "福岡県")
appliance_smartphone_camera_1.children.create([{name: "福岡フェザントカントリークラブ【アコーディア・ゴルフ】"},{name: "かほゴルフクラブ【アコーディア・ゴルフ】"},{name: "ムーンレイクゴルフクラブ 鞍手コース【PGM】"},{name: "久留米カントリークラブ"},{name: "ザ・クイーンズヒルゴルフクラブ"},{name: "セブンミリオンカントリークラブ"},{name: "九州カンツリー倶楽部春日原ゴルフ場"},{name: "九州ゴルフ倶楽部 八幡コース"}])
appliance_smartphone_camera_2 = appliance_smartphone_camera.children.create(name: "佐賀県")
appliance_smartphone_camera_2.children.create([{name: "佐賀クラシックゴルフ倶楽部"},{name: "佐賀カントリー倶楽部"},{name: "佐賀ロイヤルゴルフクラブ"},{name: "若木ゴルフ倶楽部【PGM"},{name: "唐津ゴルフ倶楽部"},{name: "武雄・嬉野カントリークラブ"},{name: "日の隈カンツリークラブ"},{name: "嘉瀬川リバーサイドゴルフ場"}])
appliance_smartphone_camera_3 = appliance_smartphone_camera.children.create(name: "長崎県")
appliance_smartphone_camera_3.children.create([{name: "パサージュ琴海アイランドゴルフクラブ"},{name: "ハウステンボスカントリークラブ【アコーディア・ゴルフ】"},{name: "大村湾カントリー倶楽部 ゴルフ場"},{name: "オーシャンパレスゴルフクラブ＆リゾート"},{name: "ペニンシュラオーナーズゴルフクラブ"},{name: "佐世保国際カントリー倶楽部【アコーディア・ゴルフ】"},{name: "喜々津カントリー倶楽部"},{name: "長崎国際ゴルフ倶楽部"}])
appliance_smartphone_camera_4 = appliance_smartphone_camera.children.create(name: "熊本県")
appliance_smartphone_camera_4.children.create([{name: "阿蘇大津ゴルフクラブ"},{name: "くまもと中央カントリークラブ"},{name: "熊本空港カントリークラブ"},{name: "司菊水ゴルフクラブ"},{name: "阿蘇リゾートグランヴィリオゴルフ場"},{name: "グリーンランドリゾートゴルフコース"},{name: "九州ゴルフ倶楽部小岱山コース"}])
appliance_smartphone_camera_5 = appliance_smartphone_camera.children.create(name: "大分県")
appliance_smartphone_camera_5.children.create([{name: "大分サニーヒルゴルフ倶楽部"},{name: "大分東急ゴルフクラブ"},{name: "大分中央ゴルフクラブ"},{name: "白木ゴルフ倶楽部"},{name: "大分カントリークラブ月形コース"},{name: "大分パブリックゴルフ場"},{name: "大分ななせゴルフ倶楽部"},{name: "城島高原ゴルフクラブ"}])
appliance_smartphone_camera_6 = appliance_smartphone_camera.children.create(name: "宮崎県")
appliance_smartphone_camera_6.children.create([{name: "宮崎レイクサイドゴルフ倶楽部"},{name: "愛和宮崎ゴルフクラブ"},{name: "宮崎大淀カントリークラブ"},{name: "延岡ゴルフクラブ"},{name: "ハイビスカスゴルフクラブ"},{name: "トム・ワトソン ゴルフコース"},{name: "宮崎座論梅ゴルフクラブ"},{name: "フェニックスカントリークラブ"}])
appliance_smartphone_camera_7 = appliance_smartphone_camera.children.create(name: "鹿児島県")
appliance_smartphone_camera_7.children.create([{name: "かごしま空港３６カントリークラブ"},{name: "鹿児島国際ゴルフ倶楽部"},{name: "霧島ゴルフクラブ"},{name: "祁答院 ゴルフクラブ"},{name: "鹿児島ガーデンゴルフ倶楽部"},{name: "いぶすきゴルフクラブ開聞コース"},{name: "鹿児島高牧カントリークラブ"},{name: "鹿児島ゴルフリゾート"}])
# appliance_smartphone_camera_8 = appliance_smartphone_camera.children.create(name: "冷暖房/空調")
# appliance_smartphone_camera_8.children.create([{name: "エアコン"},{name: "空気清浄器"},{name: "加湿器"},{name: "扇風機"},{name: "除湿機"},{name: "ファンヒーター"},{name: "電気ヒーター"},{name: "オイルヒーター"},{name: "ストーブ"},{name: "ホットカーペット"},{name: "こたつ"},{name: "電気毛布"},{name: "その他"}])
# appliance_smartphone_camera_9 = appliance_smartphone_camera.children.create(name: "生活家電")
# appliance_smartphone_camera_9.children.create([{name: "冷蔵庫"},{name: "洗濯機"},{name: "炊飯器"},{name: "電子レンジ/オーブン"},{name: "調理機器"},{name: "アイロン"},{name: "掃除機"},{name: "エスプレッソマシン"},{name: "コーヒーメーカー"},{name: "衣類乾燥機"},{name: "その他"}])
# appliance_smartphone_camera_10 = appliance_smartphone_camera.children.create(name: "その他")
# appliance_smartphone_camera_10.children.create([{name: "その他"}])

sport_leisure = Category.create(name: "沖縄地方")
sport_leisure_1 = sport_leisure.children.create(name: "沖縄県")
sport_leisure_1.children.create([{name: "沖縄カントリークラブ"},{name: "ＰＧＭゴルフリゾート沖縄【GRAND PGM】"},{name: "パームヒルズゴルフリゾートクラブ【アコーディア・ゴルフ"},{name: "那覇ゴルフクラブ"},{name: "オリオン嵐山ゴルフ倶楽部"},{name: "沖縄ロイヤルゴルフクラブ"},{name: "美らオーチャードゴルフ倶楽部"},{name: "ジ・アッタテラス ゴルフリゾート"}])
# sport_leisure_2 = sport_leisure.children.create(name: "フィッシング")
# sport_leisure_2.children.create([{name: "ロッド"},{name: "リール"},{name: "ルアー用品"},{name: "ウエア"},{name: "釣り糸/ライン"},{name: "その他"}])
# sport_leisure_3 = sport_leisure.children.create(name: "自転車")
# sport_leisure_3.children.create([{name: "自転車本体"},{name: "ウエア"},{name: "パーツ"},{name: "アクセサリー"},{name: "バッグ"},{name: "工具/メンテナンス"},{name: "その他"}])
# sport_leisure_4 = sport_leisure.children.create(name: "トレーニング/エクササイズ")
# sport_leisure_4.children.create([{name: "ランニング"},{name: "ウォーキング"},{name: "ヨガ"},{name: "トレーニング用品"},{name: "その他"}])
# sport_leisure_5 = sport_leisure.children.create(name: "野球")
# sport_leisure_5.children.create([{name: "ウェア"},{name: "シューズ"},{name: "グローブ"},{name: "バット"},{name: "アクセサリー"},{name: "防具"},{name: "練習機器"},{name: "記念グッズ"},{name: "応援グッズ"},{name: "その他"}])
# sport_leisure_6 = sport_leisure.children.create(name: "サッカー/フットサル")
# sport_leisure_6.children.create([{name: "ウェア"},{name: "シューズ"},{name: "ボール"},{name: "アクセサリー"},{name: "記念グッズ"},{name: "応援グッズ"},{name: "その他"}])
# sport_leisure_7 = sport_leisure.children.create(name: "テニス")
# sport_leisure_7.children.create([{name: "ラケット(硬式用)"},{name: "ラケット(軟式用)"},{name: "ウェア"},{name: "シューズ"},{name: "ボール"},{name: "アクセサリー"},{name: "記念グッズ"},{name: "応援グッズ"},{name: "その他"}])
# sport_leisure_8 = sport_leisure.children.create(name: "スノーボード")
# sport_leisure_8.children.create([{name: "ボード"},{name: "バインディング"},{name: "ブーツ(男性用)"},{name: "ブーツ(女性用)"},{name: "ブーツ(子ども用)"},{name: "ウエア/装備(男性用)"},{name: "ウエア/装備(女性用)"},{name: "ウエア/装備(子ども用)"},{name: "アクセサリー"},{name: "バッグ"},{name: "その他"}])
# sport_leisure_9 = sport_leisure.children.create(name: "スキー")
# sport_leisure_9.children.create([{name: "板"},{name: "ブーツ(男性用)"},{name: "ブーツ(女性用)"},{name: "ブーツ(子ども用)"},{name: "ビンディング"},{name: "ウエア(男性用)"},{name: "ウエア(女性用)"},{name: "ウエア(子ども用)"},{name: "ストック"},{name: "その他"}])
# sport_leisure_10 = sport_leisure.children.create(name: "その他スポーツ")
# sport_leisure_10.children.create([{name: "ダンス/バレエ"},{name: "サーフィン"},{name: "バスケットボール"},{name: "バドミントン"},{name: "バレーボール"},{name: "スケートボード"},{name: "陸上競技"},{name: "ラグビー"},{name: "アメリカンフットボール"},{name: "ボクシング"},{name: "ボウリング"},{name: "その他"}])
# sport_leisure_11 = sport_leisure.children.create(name: "アウトドア")
# sport_leisure_11.children.create([{name: "テント/タープ"},{name: "ライト/ランタン"},{name: "寝袋/寝具"},{name: "テーブル/チェア"},{name: "ストーブ/コンロ"},{name: "調理器具"},{name: "食器"},{name: "登山用品"},{name: "その他"}])
# sport_leisure_12 = sport_leisure.children.create(name: "その他")
# sport_leisure_12.children.create([{name: "旅行用品"},{name: "その他"}])

# handmade = Category.create(name: "ハンドメイド")
# handmade_1 = handmade.children.create(name: "アクセサリー(女性用)")
# handmade_1.children.create([{name: "ピアス"},{name: "イヤリング"},{name: "ネックレス"},{name: "ブレスレット"},{name: "リング"},{name: "チャーム"},{name: "ヘアゴム"},{name: "アンクレット"},{name: "その他"}])
# handmade_2 = handmade.children.create(name: "ファッション/小物")
# handmade_2.children.create([{name: "バッグ(女性用)"},{name: "バッグ(男性用)"},{name: "財布(女性用)"},{name: "財布(男性用)"},{name: "ファッション雑貨"},{name: "その他"}])
# handmade_3 = handmade.children.create(name: "アクセサリー/時計")
# handmade_3.children.create([{name: "アクセサリー(男性用)"},{name: "時計(女性用)"},{name: "時計(男性用)"},{name: "その他"}])
# handmade_4 = handmade.children.create(name: "日用品/インテリア")
# handmade_4.children.create([{name: "キッチン用品"},{name: "家具"},{name: "文房具"},{name: "アート/写真"},{name: "アロマ/キャンドル"},{name: "フラワー/ガーデン"},{name: "その他"}])
# handmade_5 = handmade.children.create(name: "趣味/おもちゃ")
# handmade_5.children.create([{name: "クラフト/布製品"},{name: "おもちゃ/人形"},{name: "その他"}])
# handmade_6 = handmade.children.create(name: "キッズ/ベビー")
# handmade_6.children.create([{name: "ファッション雑貨"},{name: "スタイ/よだれかけ"},{name: "外出用品"},{name: "ネームタグ"},{name: "その他"}])
# handmade_7 = handmade.children.create(name: "素材/材料")
# handmade_7.children.create([{name: "各種パーツ"},{name: "生地/糸"},{name: "型紙/パターン"},{name: "その他"}])
# handmade_8 = handmade.children.create(name: "二次創作物")
# handmade_8.children.create([{name: "Ingress"},{name: "クリエイターズ宇宙兄弟"},{name: "その他"},{name: "チケット"},{name: "すべて"}])
# handmade_9 = handmade.children.create(name: "その他")
# handmade_9.children.create([{name: "すべて"}])

# ticket = Category.create(name: "チケット")
# ticket_1 = ticket.children.create(name: "音楽")
# ticket_1.children.create([{name: "男性アイドル"},{name: "女性アイドル"},{name: "韓流"},{name: "国内アーティスト"},{name: "海外アーティスト"},{name: "音楽フェス"},{name: "声優/アニメ"},{name: "その他"}])
# ticket_2 = ticket.children.create(name: "スポーツ")
# ticket_2.children.create([{name: "サッカー"},{name: "野球"},{name: "テニス"},{name: "格闘技/プロレス"},{name: "相撲/武道"},{name: "ゴルフ"},{name: "バレーボール"},{name: "バスケットボール"},{name: "モータースポーツ"},{name: "ウィンタースポーツ"},{name: "その他"}])
# ticket_3 = ticket.children.create(name: "演劇/芸能")
# ticket_3.children.create([{name: "ミュージカル"},{name: "演劇"},{name: "伝統芸能"},{name: "落語"},{name: "お笑い"},{name: "オペラ"},{name: "サーカス"},{name: "バレエ"},{name: "その他"}])
# ticket_4 = ticket.children.create(name: "イベント")
# ticket_4.children.create([{name: "声優/アニメ"},{name: "キッズ/ファミリー"},{name: "トークショー/講演会"},{name: "その他"}])
# ticket_5 = ticket.children.create(name: "映画")
# ticket_5.children.create([{name: "邦画"},{name: "洋画"},{name: "その他"}])
# ticket_6 = ticket.children.create(name: "施設利用券")
# ticket_6.children.create([{name: "遊園地/テーマパーク"},{name: "美術館/博物館"},{name: "スキー場"},{name: "ゴルフ場"},{name: "フィットネスクラブ"},{name: "プール"},{name: "ボウリング場"},{name: "水族館"},{name: "動物園"},{name: "その他"}])
# ticket_7 = ticket.children.create(name: "優待券/割引券")
# ticket_7.children.create([{name: "ショッピング"},{name: "レストラン/食事券"},{name: "フード/ドリンク券"},{name: "宿泊券"},{name: "その他"}])
# ticket_8 = ticket.children.create(name: "その他")
# ticket_8.children.create([{name: "すべて"}])


# car_motorcycle = Category.create(name: "自動車・オートバイ")
# car_motorcycle_1 = car_motorcycle.children.create(name: "自動車本体")
# car_motorcycle_1.children.create([{name: "国内自動車本体"},{name: "外国自動車本体"}])
# car_motorcycle_2 = car_motorcycle.children.create(name: "自動車タイヤ/ホイール")
# car_motorcycle_2.children.create([{name: "タイヤ/ホイールセット"},{name: "タイヤ"},{name: "ホイール"},{name: "その他"}])
# car_motorcycle_3 = car_motorcycle.children.create(name: "自動車パーツ")
# car_motorcycle_3.children.create([{name: "サスペンション"},{name: "ブレーキ"},{name: "外装、エアロパーツ"},{name: "ライト"},{name: "内装品、シート"},{name: "ステアリング"},{name: "マフラー・排気系"},{name: "エンジン、過給器、冷却装置"},{name: "クラッチ、ミッション、駆動系"},{name: "電装品"},{name: "補強パーツ"},{name: "汎用パーツ"},{name: "外国自動車用パーツ"},{name: "その他"}])
# car_motorcycle_4 = car_motorcycle.children.create(name: "自動車アクセサリー")
# car_motorcycle_4.children.create([{name: "車内アクセサリー"},{name: "カーナビ"},{name: "カーオーディオ"},{name: "車外アクセサリー"},{name: "メンテナンス用品"},{name: "チャイルドシート"},{name: "ドライブレコーダー"},{name: "レーダー探知機"},{name: "カタログ/マニュアル"},{name: "セキュリティ"},{name: "ETC"},{name: "その他"}])
# car_motorcycle_5 = car_motorcycle.children.create(name: "オートバイ車体")
# car_motorcycle_5.children.create([{name: "すべて"}])
# car_motorcycle_6 = car_motorcycle.children.create(name: "オートバイパーツ")
# car_motorcycle_6.children.create([{name: "タイヤ"},{name: "マフラー"},{name: "エンジン、冷却装置"},{name: "カウル、フェンダー、外装"},{name: "サスペンション"},{name: "ホイール"},{name: "シート"},{name: "ブレーキ"},{name: "タンク"},{name: "ライト、ウィンカー"},{name: "チェーン、スプロケット、駆動系"},{name: "メーター"},{name: "電装系"},{name: "ミラー"},{name: "外国オートバイ用パーツ"},{name: "その他"}])
# car_motorcycle_7 = car_motorcycle.children.create(name: "オートバイアクセサリー")
# car_motorcycle_7.children.create([{name: "ヘルメット/シールド"},{name: "バイクウエア/装備"},{name: "アクセサリー"},{name: "メンテナンス"},{name: "カタログ/マニュアル"},{name: "その他"}])

# others = Category.create(name: "その他")
# others_1 = others.children.create(name: "まとめ売り")
# others_1.children.create([{name: "すべて"}])
# others_2 = others.children.create(name: "ペット用品")
# others_2.children.create([{name: "ペットフード"},{name: "犬用品"},{name: "猫用品"},{name: "魚用品/水草"},{name: "小動物用品"},{name: "爬虫類/両生類用品"},{name: "かご/おり"},{name: "鳥用品"},{name: "虫類用品"},{name: "その他"}])
# others_3 = others.children.create(name: "食品")
# others_3.children.create([{name: "菓子"},{name: "米"},{name: "野菜"},{name: "果物"},{name: "調味料"},{name: "魚介類(加工食品)"},{name: "肉類(加工食品)"},{name: "その他 加工食品"},{name: "その他"}])
# others_4 = others.children.create(name: "飲料/酒")
# others_4.children.create([{name: "コーヒー"},{name: "ソフトドリンク"},{name: "ミネラルウォーター"},{name: "茶"},{name: "ウイスキー"},{name: "ワイン"},{name: "ブランデー"},{name: "焼酎"},{name: "日本酒"},{name: "ビール、発泡酒"},{name: "その他"}])
# others_5 = others.children.create(name: "日用品/生活雑貨/旅行")
# others_5.children.create([{name: "タバコグッズ"},{name: "タオル/バス用品"},{name: "日用品/生活雑貨"},{name: "洗剤/柔軟剤"},{name: "旅行用品"},{name: "防災関連グッズ"},{name: "その他"}])
# others_6 = others.children.create(name: "アンティーク/コレクション")
# others_6.children.create([{name: "雑貨"},{name: "工芸品"},{name: "家具"},{name: "印刷物"},{name: "その他"}])
# others_7 = others.children.create(name: "文房具/事務用品")
# others_7.children.create([{name: "筆記具"},{name: "ノート/メモ帳"},{name: "テープ/マスキングテープ"},{name: "カレンダー/スケジュール"},{name: "アルバム/スクラップ"},{name: "ファイル/バインダー"},{name: "はさみ/カッター"},{name: "カードホルダー/名刺管理"},{name: "のり/ホッチキス"},{name: "その他"}])
# others_8 = others.children.create(name: "事務/店舗用品")
# others_8.children.create([{name: "オフィス用品一般"},{name: "オフィス家具"},{name: "店舗用品"},{name: "OA機器"},{name: "ラッピング/包装"},{name: "その他"}])
# others_9 = others.children.create(name: "その他")
# others_9.children.create([{name: "すべて"}])
